# Data Science with Python: Week 5

Alexander L. Hayes

## numpy

* scientific computing with Python.

In [4]:
import numpy as np

# Create Arrays
a = np.array([1, 2, 3])
b = np.array([2, 3, 5, 7])

# We can see the bytes per item
print(a.itemsize)

# Bytes for a whole array
print(a.nbytes)

# numpy automatically casts data to the datatype of the array!
a = np.arange(10)
# First three elements.
print(a[1:4])
# Negative slicing.
print(a[-1:1])

8
24
[1 2 3]
[]


In [7]:
# "Where" function
# Flattening arrays
# Reshape arrays by copying (so long as the dimensions match)
# Reduce
# Outer
# Broadcasting: Operating on arrays where dimensions do not match?

## pandas

* http://pandas.pydata.com
* "high-performance, easy-to-use data structures and data analysis tools."
* similar to abilities to SQL

Data structures include "series" and "data frames."

In [8]:
import pandas as pd

pd.Series([1, 2, 3, 5, 7, np.NaN])

0    1.0
1    2.0
2    3.0
3    5.0
4    7.0
5    NaN
dtype: float64

In [18]:
dates = pd.date_range('20171001', periods=10)

df = pd.DataFrame(np.random.randn(10, 6), index=dates, columns=pd.Series(['a', 'b', 'c', 'd', 'e', 'f']))

print(df.head(2)) # First two rows
print('...')
print(df.tail(2)) # Last two rows

print('\nPerhaps we are only interested in the columsns:\n', df.columns)
print('\nPerhaps we just want the values in the data itself:\n', df.values)

# Sort by index or values:
# missing

                   a         b         c         d         e         f
2017-10-01 -0.291942 -0.618230  0.585356  0.557813 -0.122150 -0.406016
2017-10-02  0.404419 -0.178326 -1.041093 -0.502673  0.255708 -1.407318
...
                   a         b         c         d         e         f
2017-10-09 -0.316267  1.034005 -0.330447 -0.132116  0.599037  0.831127
2017-10-10  1.400917 -0.722037 -0.530590 -0.913328  1.149034 -0.184642

Perhaps we are only interested in the columsns:
 Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

Perhaps we just want the values in the data itself:
 [[-0.29194222 -0.6182298   0.58535631  0.55781259 -0.12214956 -0.40601612]
 [ 0.404419   -0.17832564 -1.04109271 -0.50267286  0.25570844 -1.40731775]
 [-1.66922823  0.12357437  0.47227983  0.96288867  0.58992259  0.51551452]
 [-0.07949513 -0.11406532  0.13062321 -0.56319362 -0.08616227 -0.22701391]
 [-1.10378477  0.41203223  0.78358366 -0.01288373  1.07717748 -0.69111108]
 [ 0.22321895 -0.70450319  0.84428125